changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Skill Changes
      labels:
        - skill
        - behavior
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
